var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};
$jscomp.getConstructImplementation=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=$jscomp.objectCreate(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||
e}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};$jscomp.polyfill("Reflect",function(a){return a?a:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(a){return $jscomp.construct},"es6","es3");
$jscomp.polyfill("Reflect.setPrototypeOf",function(a){if(a)return a;if($jscomp.setPrototypeOf){var b=$jscomp.setPrototypeOf;return function(c,d){try{return b(c,d),!0}catch(e){return!1}}}return null},"es6","es5");OV.GetNameOrDefault=function(a,b){return 0<a.length?a:b};OV.GetMeshName=function(a){return OV.GetNameOrDefault(a,"No Name")};OV.GetMaterialName=function(a){return OV.GetNameOrDefault(a,"No Name")};OV.IsHoverEnabled=function(){return window.matchMedia("(hover : hover)").matches?!0:!1};
OV.IsSmallWidth=function(){return window.matchMedia("(max-width : 700px)").matches?!0:!1};OV.IsSmallHeight=function(){return window.matchMedia("(max-height : 700px)").matches?!0:!1};
OV.InstallTooltip=function(a,b){if(OV.IsHoverEnabled()){var c=$(document.body),d=null;a.hover(function(){var e=d=$("<div>").html(b).addClass("ov_tooltip").appendTo(c),f=e.offset,g=d,h=$(window).outerWidth(!0),l=a.offset(),k=a.outerWidth(!0),n=a.outerHeight(!0);g=g.outerWidth(!0);k=l.left+k/2-g/2;k+g>h-10&&(k=h-g-10);10>k&&(k=10);k=Math.max(k,0);f.call(e,{left:k,top:l.top+n+10})},function(){d.remove()})}};
OV.CopyToClipboard=function(a){var b=document.createElement("input");b.style.position="absolute";b.style.left="0";b.style.top="0";b.setAttribute("value",a);document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)};OV.DownloadArrayBufferAsFile=function(a,b){var c=document.createElement("a");c.href=OV.CreateObjectUrl(a);c.download=b;document.body.appendChild(c);c.click();document.body.removeChild(c)};
OV.CreateIconButton=function(a,b,c,d){var e=$("<a>");e.attr("href",d);e.attr("target","_blank");e.attr("rel","noopener noreferrer");OV.InstallTooltip(e,c);var f=$("<img>").attr("src",a).appendTo(e);null!==b&&OV.IsHoverEnabled()&&e.hover(function(){f.attr("src",b)},function(){f.attr("src",a)});return e};OV.ToolbarButton=function(a,b,c){this.image=a;this.imageTitle=b;this.onClick=c;this.selected=!1;this.buttonImg=this.buttonDiv=null};OV.ToolbarButton.prototype.CreateDomElement=function(a){this.buttonDiv=$("<div>").addClass("ov_toolbar_button_div").appendTo(a);this.buttonImg=$("<img>").addClass("ov_toolbar_button").appendTo(this.buttonDiv);this.buttonImg.attr("src",this.image);null!==this.onClick&&this.buttonDiv.click(this.onClick);OV.InstallTooltip(this.buttonDiv,this.imageTitle);this.Update()};
OV.ToolbarButton.prototype.AddClass=function(a){this.buttonDiv.addClass(a)};OV.ToolbarButton.prototype.Update=function(){this.selected?this.buttonDiv.addClass("selected"):this.buttonDiv.removeClass("selected")};OV.Toolbar=function(a){this.mainDiv=$("<div>").addClass("ov_toolbar").appendTo(a)};OV.Toolbar.prototype.AddImageButton=function(a,b,c){a=new OV.ToolbarButton(a,b,c);a.CreateDomElement(this.mainDiv);return a};
OV.Toolbar.prototype.AddImageRadioButton=function(a,b,c){for(var d=[],e={$jscomp$loop$prop$buttonIndex$12:0};e.$jscomp$loop$prop$buttonIndex$12<a.length;e={$jscomp$loop$prop$buttonIndex$12:e.$jscomp$loop$prop$buttonIndex$12},e.$jscomp$loop$prop$buttonIndex$12++){var f=a[e.$jscomp$loop$prop$buttonIndex$12];f=this.AddImageButton(f.image,f.title,function(g){return function(){for(var h=0;h<d.length;h++){var l=d[h];l.selected=h===g.$jscomp$loop$prop$buttonIndex$12?!0:!1;l.Update()}c(g.$jscomp$loop$prop$buttonIndex$12)}}(e));
b===e.$jscomp$loop$prop$buttonIndex$12&&(f.selected=!0,f.Update());d.push(f)}return d};OV.Toolbar.prototype.AddSeparator=function(){return $("<div>").addClass("ov_toolbar_separator").appendTo(this.mainDiv)};OV.ScrollToView=function(a){a[0].scrollIntoView({behavior:"smooth",block:"nearest"})};OV.TreeViewButton=function(a){this.imagePath=a;this.clickHandler=this.domElement=null};OV.TreeViewButton.prototype.SetImage=function(a){this.imagePath=a;this.domElement.attr("src",this.imagePath)};OV.TreeViewButton.prototype.OnClick=function(a){this.clickHandler=a};
OV.TreeViewButton.prototype.CreateDomElement=function(a){this.domElement=$("<img>").addClass("ov_tree_menu_item_button").appendTo(a);this.domElement.attr("src",this.imagePath);null!==this.clickHandler&&this.domElement.click(this.clickHandler)};OV.TreeViewItem=function(a){this.name=a;this.nameElement=this.mainElement=null};OV.TreeViewItem.prototype.GetName=function(){return this.name};OV.TreeViewItem.prototype.SetName=function(a){this.name=a};
OV.TreeViewItem.prototype.CreateMainElement=function(a){this.mainElement=$("<div>").addClass("ov_tree_menu_item").attr("title",this.name).appendTo(a)};OV.TreeViewItem.prototype.CreateNameElement=function(){this.nameElement=$("<div>").addClass("ov_tree_menu_item_name").html(this.name).appendTo(this.mainElement)};OV.TreeViewSingleItem=function(a){OV.TreeViewItem.call(this,a);this.parent=null;this.selected=!1};$jscomp.inherits(OV.TreeViewSingleItem,OV.TreeViewItem);
OV.TreeViewSingleItem.prototype.SetSelected=function(a){if(this.selected=a){var b=this;this.mainElement.addClass("selected");this.parent.ShowChildren(!0,function(){OV.ScrollToView(b.mainElement)})}else this.mainElement.removeClass("selected")};OV.TreeViewSingleItem.prototype.SetParent=function(a){this.parent=a};OV.TreeViewSingleItem.prototype.CreateDomElement=function(a){this.CreateMainElement(a);this.CreateNameElement()};
OV.TreeViewButtonItem=function(a){OV.TreeViewSingleItem.call(this,a);this.buttons=[];this.onNameClick=null};$jscomp.inherits(OV.TreeViewButtonItem,OV.TreeViewSingleItem);OV.TreeViewButtonItem.prototype.OnNameClick=function(a){this.onNameClick=a};OV.TreeViewButtonItem.prototype.AddButton=function(a){this.buttons.push(a)};
OV.TreeViewButtonItem.prototype.CreateDomElement=function(a){this.CreateMainElement(a);this.mainElement.addClass("clickable");a=$("<div>").addClass("ov_tree_menu_item_button_container").appendTo(this.mainElement);for(var b=0;b<this.buttons.length;b++)this.buttons[b].CreateDomElement(a);this.CreateNameElement();if(null!==this.onNameClick){var c=this;this.nameElement.css("cursor","pointer");this.nameElement.click(function(d){c.onNameClick()})}};
OV.TreeViewGroupItem=function(a,b){OV.TreeViewItem.call(this,a);this.iconPath=b;this.childrenDiv=null;this.showChildren=!1;this.openCloseButton=null;this.openButtonPath="assets/images/tree/arrow_down.svg";this.closeButtonPath="assets/images/tree/arrow_up.svg";this.animated=!0;this.openCloseHandler=null};$jscomp.inherits(OV.TreeViewGroupItem,OV.TreeViewItem);OV.TreeViewGroupItem.prototype.GetName=function(){return this.name};OV.TreeViewGroupItem.prototype.SetName=function(a){this.name=a};
OV.TreeViewGroupItem.prototype.SetAnimated=function(a){this.animated=a};OV.TreeViewGroupItem.prototype.SetOpenCloseHandler=function(a){this.openCloseHandler=a};
OV.TreeViewGroupItem.prototype.ShowChildren=function(a,b){this.showChildren=a;null!==this.childrenDiv&&(a?(this.openCloseButton.attr("src",this.openButtonPath),this.animated?this.childrenDiv.slideDown(400,b):(this.childrenDiv.show(),b&&b())):(this.openCloseButton.attr("src",this.closeButtonPath),this.animated?this.childrenDiv.slideUp(400,b):(this.childrenDiv.hide(),b&&b())))};
OV.TreeViewGroupItem.prototype.CreateChildrenDiv=function(){if(null===this.childrenDiv){var a=this;this.childrenDiv=$("<div>").addClass("ov_tree_menu_children").insertAfter(this.mainElement);this.mainElement.addClass("clickable");this.ShowChildren(this.showChildren,null);this.mainElement.click(function(b){a.showChildren=!a.showChildren;a.ShowChildren(a.showChildren,null);null!==a.openCloseHandler&&a.openCloseHandler()})}return this.childrenDiv};OV.TreeViewGroupItem.prototype.GetChildrenDiv=function(){return this.childrenDiv};
OV.TreeViewGroupItem.prototype.AddChild=function(a){this.CreateChildrenDiv();a.SetParent(this);a.CreateDomElement(this.childrenDiv)};
OV.TreeViewGroupItem.prototype.CreateDomElement=function(a){this.CreateMainElement(a);$("<img>").addClass("ov_tree_menu_item_icon").attr("src",this.iconPath).appendTo(this.mainElement);a=$("<div>").addClass("ov_tree_menu_item_button_container").appendTo(this.mainElement);this.openCloseButton=$("<img>").addClass("ov_tree_menu_item_button").attr("src",this.openButtonPath).appendTo(a);this.CreateNameElement()};OV.TreeView=function(a){this.mainDiv=$("<div>").addClass("ov_tree_menu").appendTo(a)};
OV.TreeView.prototype.AddItem=function(a){a.CreateDomElement(this.mainDiv)};OV.TreeView.prototype.Clear=function(){this.mainDiv.empty()};OV.Modal=function(){this.modalDiv=$("<div>").css("position","absolute");this.closeHandler=this.customResizeHandler=this.resizeHandler=this.overlayDiv=null;this.isOpen=!1;this.closeable=!0};OV.Modal.prototype.GetContentDiv=function(){return this.modalDiv};OV.Modal.prototype.SetCloseable=function(a){this.closeable=a};OV.Modal.prototype.SetCustomResizeHandler=function(a){this.customResizeHandler=a};OV.Modal.prototype.SetCloseHandler=function(a){this.closeHandler=a};
OV.Modal.prototype.Open=function(){var a=$(window),b=$(document.body);this.overlayDiv=$("<div>").addClass("ov_modal_overlay").css("position","absolute").appendTo(b);this.modalDiv.appendTo(b);this.resizeHandler=this.Resize.bind(this);a.bind("resize",this.resizeHandler);if(this.closeable){var c=this;this.overlayDiv.click(function(d){c.Close()})}this.isOpen=!0;this.Resize()};
OV.Modal.prototype.Close=function(){this.isOpen&&($(window).unbind("resize",this.resizeHandler),null!==this.closeHandler&&this.closeHandler(),this.modalDiv.remove(),this.overlayDiv.remove(),this.resizeHandler=this.overlayDiv=null,this.isOpen=!1)};OV.Modal.prototype.IsOpen=function(){return this.isOpen};
OV.Modal.prototype.Resize=function(){var a=$(window),b=a.outerWidth();a=a.outerHeight();this.overlayDiv.width(b);this.overlayDiv.height(a);this.overlayDiv.offset({left:0,top:0});this.customResizeHandler?this.customResizeHandler(this.modalDiv):this.modalDiv.offset({left:(b-this.modalDiv.outerWidth())/2,top:(a-this.modalDiv.outerHeight())/3})};OV.ProgressDialog=function(){this.modal=new OV.Modal;this.modal.SetCloseable(!1);this.textDiv=this.imageDiv=null};OV.ProgressDialog.prototype.SetText=function(a){this.textDiv.html(a)};
OV.ProgressDialog.prototype.Show=function(a){var b=this.modal.GetContentDiv();b.addClass("ov_progress");this.imageDiv=$("<img>").addClass("ov_progress_img").attr("src","assets/images/3dviewer_net_logo.svg").appendTo(b);this.textDiv=$("<div>").addClass("ov_progress_text").appendTo(b);this.SetText(a);this.modal.Open()};OV.ProgressDialog.prototype.Hide=function(){this.modal.Close()};OV.ButtonDialog=function(){this.modal=new OV.Modal};
OV.ButtonDialog.prototype.Init=function(a,b){function c(f,g){g=$("<div>").addClass("ov_dialog_button").html(f.name).appendTo(g);f.subClass&&g.addClass(f.subClass);g.click(function(){f.onClick()})}var d=this.modal.GetContentDiv();d.addClass("ov_dialog");$("<div>").addClass("ov_dialog_title").html(a).appendTo(d);a=$("<div>").addClass("ov_dialog_content").appendTo(d);d=$("<div>").addClass("ov_dialog_buttons").appendTo(d);d=$("<div>").addClass("ov_dialog_buttons_inner").appendTo(d);for(var e=0;e<b.length;e++)c(b[e],
d);return a};OV.ButtonDialog.prototype.SetCloseHandler=function(a){this.modal.SetCloseHandler(a)};OV.ButtonDialog.prototype.Show=function(){this.modal.Open()};OV.ButtonDialog.prototype.Hide=function(){this.modal.Close()};OV.ListPopup=function(){this.modal=new OV.Modal;this.listDiv=null};OV.ListPopup.prototype.Init=function(){var a=this.modal.GetContentDiv();a.addClass("ov_popup");this.listDiv=$("<div>").addClass("ov_popup_list").addClass("ov_thin_scrollbar").appendTo(a)};
OV.ListPopup.prototype.SetCustomResizeHandler=function(a){this.modal.SetCustomResizeHandler(a)};OV.ListPopup.prototype.AddListItem=function(a,b){var c=$("<div>").addClass("ov_popup_list_item").appendTo(this.listDiv);a.color&&$("<div>").addClass("ov_popup_list_item_rgbbox").css("background","#"+a.color).appendTo(c);$("<div>").addClass("ov_popup_list_item_name").html(a.name).appendTo(c);c.click(b.onClick);OV.IsHoverEnabled()&&b.onHoverStart&&b.onHoverStop&&c.hover(function(){b.onHoverStart()},function(){b.onHoverStop()})};
OV.ListPopup.prototype.Show=function(){this.modal.Open()};OV.ListPopup.prototype.Hide=function(){this.modal.Close()};OV.FeatureSet={SetDefaultColor:!1};OV.ShowMessageDialog=function(a,b,c){var d=new OV.ButtonDialog;a=d.Init(a,[{name:"OK",onClick:function(){d.Hide()}}]);$("<div>").addClass("ov_dialog_message").html(b).appendTo(a);null!==c&&$("<div>").addClass("ov_dialog_submessage").html("<i>"+c+"</i>").appendTo(a);d.Show();return d};
OV.ShowOpenUrlDialog=function(a){function b(f){for(var g=0;g<f.length;g++){var h=f[g];if(-1!==h.search(/www\.dropbox\.com/u)){h=h.replace("www.dropbox.com","dl.dropbox.com");var l=h.indexOf("?");-1!==l&&(h=h.substr(0,l));f[g]=h}else-1!==h.search(/github\.com/u)&&(h=h.replace("github.com","raw.githubusercontent.com"),h=h.replace("/blob",""),l=h.indexOf("?"),-1!==l&&(h=h.substr(0,l)),f[g]=h)}}var c=new OV.ButtonDialog,d=$("<textarea>").addClass("ov_dialog_textarea"),e=c.Init("Open Model from Url",[{name:"Cancel",
subClass:"outline",onClick:function(){c.Hide()}},{name:"OK",onClick:function(){var f=[];OV.ReadLines(d.val(),function(g){f.push(g)});c.Hide();b(f);a(f)}}]);$("<div>").html("Here you can load models based on their urls. You can add more lines if your model builds up from multiple files.").addClass("ov_dialog_section").appendTo(e);d.appendTo(e);c.Show();return c};
OV.ShowEmbeddingDialog=function(a,b,c){function d(m,p,q){m=$("<div>").addClass("ov_dialog_table_row").appendTo(m);var r=$("<input>").attr("type","checkbox").attr("checked","true").appendTo(m);$("<span>").html(p).appendTo(m);r.change(function(){q(r.prop("checked"))})}function e(m){var p=OV.CreateUrlBuilder();p.AddModelUrls(m.files);p.AddCamera(m.camera);p.AddColor(m.color);return'<iframe width="640" height="480" style="border:1px solid #eeeeee;" src="https://3dviewer.net/embed.html#'+(p.GetParameterList()+
'"></iframe>')}if(!a.IsOnlyFileSource(OV.FileSource.Url))return OV.ShowMessageDialog("Embedding Failed","Embedding works only if you load files by url. Please upload your model files to a web server, open them by url, and try embedding again.",null);a=a.GetFileList().GetFiles();for(var f=[],g=0;g<a.length;g++)f.push(a[g].fileUrl);var h={files:f,camera:c,color:null},l=new OV.ButtonDialog,k=$("<textarea>").attr("readonly","true").addClass("ov_dialog_textarea");a=l.Init("Embedding",[{name:"Close",onClick:function(){l.Hide()}}]);
$("<div>").html("Embedding options:").addClass("ov_dialog_section").appendTo(a);f=$("<div>").addClass("ov_dialog_section").appendTo(a);d(f,"Use current camera position",function(m){h.camera=m?c:null;k.val(e(h))});OV.FeatureSet.SetDefaultColor&&(d(f,"Use overridden default color",function(m){h.color=m?b.defaultColor:null;k.val(e(h))}),h.color=b.defaultColor);k.val(e(h));k.appendTo(a);a=$("<div>").addClass("ov_dialog_inner_buttons").appendTo(a);var n=$("<div>").addClass("ov_dialog_inner_button").html("copy to clipboard").appendTo(a);
n.click(function(){OV.CopyToClipboard(k.val());n.fadeOut(200,function(){n.html("successfully copied").fadeIn(200);setTimeout(function(){n.fadeOut(200,function(){n.html("copy to clipboard").fadeIn(200)})},2E3)})});l.Show();return l};
OV.ShowSettingsDialog=function(a,b){var c={defaultColor:a.defaultColor},d=new OV.ButtonDialog;a=d.Init("Settings",[{name:"Cancel",subClass:"outline",onClick:function(){d.Hide()}},{name:"OK",onClick:function(){d.Hide();b(c)}}]);a=$("<div>").addClass("ov_dialog_table_row").appendTo(a);$("<div>").html("Default Color").addClass("ov_dialog_table_row_name").appendTo(a);a=$("<div>").addClass("ov_dialog_table_row_value").appendTo(a);var e=$("<input>").attr("type","color").addClass("ov_dialog_color").appendTo(a);
e.val("#"+OV.ColorToHexString(c.defaultColor));e.change(function(){var f=e.val().substr(1);c.defaultColor=OV.HexStringToColor(f)});d.Show();return d};
OV.ShowListPopup=function(a,b,c){var d=new OV.ListPopup;d.SetCustomResizeHandler(function(f){var g=a.offset(),h=g.left+a.outerWidth(!0);g=g.top+a.outerHeight(!0);f.offset({left:h,top:g-f.outerHeight(!0)})});d.Init();for(var e={$jscomp$loop$prop$i$16:0};e.$jscomp$loop$prop$i$16<b.length;e={$jscomp$loop$prop$i$16:e.$jscomp$loop$prop$i$16},e.$jscomp$loop$prop$i$16++)d.AddListItem(b[e.$jscomp$loop$prop$i$16],{onHoverStart:function(f){return function(){if(c.onHoverStart)c.onHoverStart(f.$jscomp$loop$prop$i$16)}}(e),
onHoverStop:function(f){return function(){if(c.onHoverStop)c.onHoverStop(f.$jscomp$loop$prop$i$16)}}(e),onClick:function(f){return function(){d.Hide();c.onClick(f.$jscomp$loop$prop$i$16)}}(e)});d.Show();return d};OV.ExportDialog=function(a){this.callbacks=a;this.model=null;this.exportFormats=[{name:"obj",formats:[{name:"text",format:OV.FileFormat.Text,extension:"obj"}]},{name:"stl",formats:[{name:"text",format:OV.FileFormat.Text,extension:"stl"},{name:"binary",format:OV.FileFormat.Binary,extension:"stl"}]},{name:"ply",formats:[{name:"text",format:OV.FileFormat.Text,extension:"ply"},{name:"binary",format:OV.FileFormat.Binary,extension:"ply"}]},{name:"gltf",formats:[{name:"text",format:OV.FileFormat.Text,extension:"gltf"},
{name:"binary",format:OV.FileFormat.Binary,extension:"glb"}]},{name:"off",formats:[{name:"text",format:OV.FileFormat.Text,extension:"off"}]}];this.formatParameters={exportFormatButtonDivs:[],formatSettingsDiv:null,selectedFormat:null}};
OV.ExportDialog.prototype.Show=function(a){if(null===a){var b=OV.ShowMessageDialog("Export Failed","Please load a model before exporting.",null);this.callbacks.onDialog(b)}else{var c=this,d=new OV.ButtonDialog,e=d.Init("Export",[{name:"Close",subClass:"outline",onClick:function(){d.Hide()}},{name:"Export",onClick:function(){null!==c.formatParameters.selectedFormat&&(d.Hide(),c.ExportFormat(a))}}]);$("<div>").html("Select a format from the below list to export your model. Please note that the export can take several second.").addClass("ov_dialog_section").appendTo(e);
b=$("<div>").addClass("ov_dialog_select").appendTo(e);this.formatParameters.formatSettingsDiv=$("<div>").addClass("ov_dialog_section").height(50).appendTo(e);for(e={$jscomp$loop$prop$i$18:0};e.$jscomp$loop$prop$i$18<this.exportFormats.length;e={$jscomp$loop$prop$i$18:e.$jscomp$loop$prop$i$18},e.$jscomp$loop$prop$i$18++){var f=this.exportFormats[e.$jscomp$loop$prop$i$18];f=$("<div>").addClass("ov_dialog_select_option").html(f.name).width(40).appendTo(b);this.formatParameters.exportFormatButtonDivs.push(f);
f.click(function(g){return function(){c.OnExportFormatSelect(g.$jscomp$loop$prop$i$18)}}(e))}this.OnExportFormatSelect(0);d.Show();this.callbacks.onDialog(d)}};
OV.ExportDialog.prototype.OnExportFormatSelect=function(a){this.formatParameters.formatSettingsDiv.empty();for(var b=0;b<this.formatParameters.exportFormatButtonDivs.length;b++){var c=this.formatParameters.exportFormatButtonDivs[b];b===a?c.addClass("selected"):c.removeClass("selected")}var d=this;a=this.exportFormats[a];b={};for(c=0;c<a.formats.length;b={$jscomp$loop$prop$format$20:b.$jscomp$loop$prop$format$20},c++){b.$jscomp$loop$prop$format$20=a.formats[c];var e=$("<div>").addClass("ov_dialog_table_row").appendTo(this.formatParameters.formatSettingsDiv),
f=$("<input>").addClass("ov_dialog_table_radio").attr("type","radio").attr("id",b.$jscomp$loop$prop$format$20.name).attr("name","format").appendTo(e);$("<label>").attr("for",b.$jscomp$loop$prop$format$20.name).html(b.$jscomp$loop$prop$format$20.name).appendTo(e);0===c&&(f.prop("checked",!0),this.formatParameters.selectedFormat=b.$jscomp$loop$prop$format$20);f.change(function(g){return function(){d.formatParameters.selectedFormat=g.$jscomp$loop$prop$format$20}}(b))}};
OV.ExportDialog.prototype.ExportFormat=function(a){var b=this.formatParameters.selectedFormat;if(null!==b){var c=this,d=new OV.ProgressDialog;d.Show("Exporting Model");OV.RunTaskAsync(function(){var e=(new OV.Exporter).Export(a,b.format,b.extension);0===e.length?d.Hide():1===e.length?(d.Hide(),e=e[0],OV.DownloadArrayBufferAsFile(e.GetContent(),e.GetName())):1<e.length&&(d.Hide(),c.ShowExportedFiles(e))})}};
OV.ExportDialog.prototype.ShowExportedFiles=function(a){var b=new OV.ButtonDialog,c=b.Init("Exported Files",[{name:"Close",onClick:function(){b.Hide()}}]);$("<div>").html("You can download your exported files here.").addClass("ov_dialog_section").appendTo(c);c=$("<div>").addClass("ov_dialog_section").appendTo(c);c=$("<div>").addClass("ov_dialog_file_list").addClass("ov_thin_scrollbar").appendTo(c);for(var d=0;d<a.length;d++){var e=a[d],f=OV.CreateObjectUrl(e.GetContent()),g=$("<a>").addClass("ov_dialog_file_link").appendTo(c);
g.attr("href",f);g.attr("download",e.GetName());$("<img>").addClass("ov_dialog_file_link_icon").attr("src","assets/images/dialog/file_download.svg").appendTo(g);$("<div>").addClass("ov_dialog_file_link_text").html(e.GetName()).appendTo(g)}b.Show();this.callbacks.onDialog(b)};OV.MaterialData=function(a){this.originalIndex=a;this.menuItem=null};OV.MaterialData.prototype.SetSelected=function(a){this.menuItem.SetSelected(a)};OV.MaterialData.prototype.CreateMenuItem=function(a,b){var c=this;this.menuItem=new OV.TreeViewButtonItem(a);this.menuItem.OnNameClick(function(){b.onSelected(c.originalIndex)});return this.menuItem};OV.MeshData=function(a){this.originalIndex=a;this.visible=!0;this.showHideButton=this.menuItem=null};OV.MeshData.prototype.IsVisible=function(){return this.visible};
OV.MeshData.prototype.SetVisible=function(a){(this.visible=a)?this.showHideButton.SetImage("assets/images/tree/visible.svg"):this.showHideButton.SetImage("assets/images/tree/hidden.svg")};OV.MeshData.prototype.SetSelected=function(a){this.menuItem.SetSelected(a)};
OV.MeshData.prototype.CreateMenuItem=function(a,b){var c=this;this.menuItem=new OV.TreeViewButtonItem(a);a=new OV.TreeViewButton("assets/images/tree/fit_tree.svg");a.OnClick(function(){b.onFitToWindow(c.originalIndex)});this.menuItem.AddButton(a);this.showHideButton=new OV.TreeViewButton("assets/images/tree/visible.svg");this.showHideButton.OnClick(function(d){if(d.ctrlKey||d.metaKey)b.onIsolate(c.originalIndex);else b.onShowHide(c.originalIndex)});this.menuItem.AddButton(this.showHideButton);this.menuItem.OnNameClick(function(){b.onSelected(c.originalIndex)});
return this.menuItem};OV.ModelData=function(){this.meshDataArr=[];this.materialDataArr=[]};OV.ModelData.prototype.MaterialCount=function(){return this.materialDataArr.length};OV.ModelData.prototype.GetMaterialData=function(a){return this.materialDataArr[a]};OV.ModelData.prototype.AddMaterialData=function(a){this.materialDataArr.push(a)};OV.ModelData.prototype.MeshCount=function(){return this.meshDataArr.length};OV.ModelData.prototype.GetMeshData=function(a){return this.meshDataArr[a]};
OV.ModelData.prototype.AddMeshData=function(a){this.meshDataArr.push(a)};OV.ModelData.prototype.Clear=function(){this.meshDataArr=[];this.materialDataArr=[]};OV.InfoPanel=function(a){this.mainDiv=$("<div>").addClass("ov_info_panel_main").appendTo(a);this.treeView=new OV.TreeView(this.mainDiv);this.detailsItem=new OV.TreeViewGroupItem("Details","assets/images/tree/details.svg");this.detailsItem.ShowChildren(!OV.IsSmallHeight(),null);this.treeView.AddItem(this.detailsItem);this.detailsItem.CreateChildrenDiv().addClass("ov_info_panel_content");this.popup=null};OV.InfoPanel.prototype.SetOpenCloseHandler=function(a){this.detailsItem.SetAnimated(!1);this.detailsItem.SetOpenCloseHandler(a)};
OV.InfoPanel.prototype.FillWithMaterialInfo=function(a,b,c){function d(m,p,q){m=$("<div>").addClass("ov_info_box_row").appendTo(m);$("<div>").addClass("ov_info_box_row_name").html(p).appendTo(m);p=$("<div>").addClass("ov_info_box_row_value").appendTo(m);q(p)}function e(m,p){d(m,p.type,function(q){q.html(p.name).attr("title",p.path)})}this.Clear();if(null!==a){var f=this.detailsItem.GetChildrenDiv(),g=$("<div>").addClass("ov_info_box").appendTo(f);d(g,"Color",function(m){var p="#"+OV.ColorToHexString(a.diffuse);
$("<div>").addClass("ov_info_box_rgbbox").css("background",p).attr("title",p).appendTo(m);$("<div>").addClass("ov_info_box_rgbtext").html(p).attr("title",p).appendTo(m)});var h=parseInt(Math.round(100*a.opacity),10)+"%";(function(m,p,q){d(m,p,function(r){r.html(q).attr("title",q)})})(g,"Opacity",h);if(0<a.textureNames.length)for(g=$("<div>").addClass("ov_info_box").appendTo(f),$("<div>").addClass("ov_info_box_title").html("Textures").appendTo(g),g=$("<div>").addClass("ov_info_box_details").appendTo(g),
h=0;h<a.textureNames.length;h++)e(g,a.textureNames[h]);var l=[];for(g=0;g<a.usedByMeshes.length;g++)h=b(a.usedByMeshes[g]),l.push({name:OV.GetMeshName(h.name)});var k=this;b="Meshes ("+l.length+")";var n=$("<div>").addClass("ov_info_box_button").html(b).appendTo(f);n.click(function(){0!==l.length&&(k.popup=OV.ShowListPopup(n,l,{onHoverStart:function(m){c.onMeshHover(a.usedByMeshes[m])},onHoverStop:function(m){c.onMeshHover(null)},onClick:function(m){c.onMeshSelect(a.usedByMeshes[m])}}))})}};
OV.InfoPanel.prototype.FillWithModelInfo=function(a,b,c){function d(n,m,p){n=$("<div>").addClass("ov_info_box_column").css("width","50%").appendTo(n);$("<div>").addClass("ov_info_box_title").html(m).appendTo(n);$("<div>").addClass("ov_info_box_content_big").html(p.toLocaleString("en-US")).appendTo(n)}this.Clear();if(null!==a){var e=this.detailsItem.GetChildrenDiv(),f=$("<div>").addClass("ov_info_box").appendTo(e);d(f,"Vertices",a.vertexCount);d(f,"Triangles",a.triangleCount);f=$("<div>").addClass("ov_info_box").appendTo(e);
$("<div>").addClass("ov_info_box_title").html("Size").appendTo(f);var g=OV.SubCoord3D(a.boundingBox.max,a.boundingBox.min);g=g.x.toFixed(1)+" x "+g.y.toFixed(1)+" x "+g.z.toFixed(1);$("<div>").addClass("ov_info_box_content").html(g).attr("title",g).appendTo(f);var h=[];for(f=0;f<a.usedMaterials.length;f++)g=b(a.usedMaterials[f]),h.push({name:OV.GetMaterialName(g.name),color:OV.ColorToHexString(g.diffuse)});var l=this;b="Materials ("+h.length+")";var k=$("<div>").addClass("ov_info_box_button").html(b).appendTo(e);
k.click(function(){l.popup=OV.ShowListPopup(k,h,{onClick:function(n){c.onMaterialSelect(a.usedMaterials[n])}})})}};OV.InfoPanel.prototype.Clear=function(){null!==this.popup&&(this.popup.Hide(),this.popup=null);this.detailsItem.GetChildrenDiv().empty()};OV.SelectionType={Material:1,Mesh:2};OV.Selection=function(a,b){this.type=a;this.index=b};
OV.Menu=function(a){this.parentDiv=a;this.callbacks=null;this.titleDiv=$("<div>").addClass("ov_menu_tree_title").addClass("ov_thin_scrollbar").appendTo(a);this.treeDiv=$("<div>").addClass("ov_menu_tree_panel").addClass("ov_thin_scrollbar").appendTo(a);this.infoDiv=$("<div>").addClass("ov_menu_info_panel").addClass("ov_thin_scrollbar").appendTo(a);this.treeView=new OV.TreeView(this.treeDiv);this.infoPanel=new OV.InfoPanel(this.infoDiv);this.modelData=new OV.ModelData;this.tempSelectedMeshIndex=this.selection=
null};OV.Menu.prototype.Init=function(a){var b=this;this.callbacks=a;this.infoPanel.SetOpenCloseHandler(function(){b.Resize()})};OV.Menu.prototype.Resize=function(){var a=this.titleDiv.outerHeight(!0),b=this.infoDiv.outerHeight(!0),c=this.parentDiv.height();this.treeDiv.outerHeight(c-b-a,!0)};
OV.Menu.prototype.FillTree=function(a){var b=this;this.titleDiv.html(a.mainFile).attr("title",a.mainFile);var c=a.model,d=a.usedFiles;a=a.missingFiles;var e=new OV.TreeViewGroupItem("Files","assets/images/tree/files.svg");this.treeView.AddItem(e);for(var f=0;f<d.length;f++){var g=new OV.TreeViewSingleItem(d[f]);e.AddChild(g)}if(0<a.length)for(d=new OV.TreeViewGroupItem("Missing Files","assets/images/tree/missing_files.svg"),this.treeView.AddItem(d),e=0;e<a.length;e++)f=new OV.TreeViewButtonItem(a[e]),
g=new OV.TreeViewButton("assets/images/tree/open.svg"),g.OnClick(function(){b.callbacks.openFileBrowserDialog()}),f.AddButton(g),d.AddChild(f);a=new OV.TreeViewGroupItem("Materials","assets/images/tree/materials.svg");this.treeView.AddItem(a);for(d=0;d<c.MaterialCount();d++)e=c.GetMaterial(d),f=OV.GetMaterialName(e.name),e=new OV.MaterialData(d),f=e.CreateMenuItem(f,{onSelected:function(h){b.SetSelection(new OV.Selection(OV.SelectionType.Material,h))}}),this.modelData.AddMaterialData(e),a.AddChild(f);
a=new OV.TreeViewGroupItem("Meshes","assets/images/tree/meshes.svg");this.treeView.AddItem(a);a.ShowChildren(!0,null);for(d=0;d<c.MeshCount();d++)f=c.GetMesh(d),e=new OV.MeshData(d),f=OV.GetMeshName(f.GetName()),f=e.CreateMenuItem(f,{onShowHide:function(h){b.ToggleMeshVisibility(h)},onIsolate:function(h){b.IsolateMesh(h)},onFitToWindow:function(h){b.FitMeshToWindow(h)},onSelected:function(h){b.SetSelection(new OV.Selection(OV.SelectionType.Mesh,h))}}),this.modelData.AddMeshData(e),a.AddChild(f);this.UpdateInfoPanel();
this.Resize()};OV.Menu.prototype.IsMeshVisible=function(a){return this.modelData.GetMeshData(a).IsVisible()};OV.Menu.prototype.IsolateMesh=function(a){for(var b=!0,c=0;c<this.modelData.MeshCount();c++){var d=this.modelData.GetMeshData(c);if(c!==a&&d.IsVisible()){b=!1;break}}for(c=0;c<this.modelData.MeshCount();c++)d=this.modelData.GetMeshData(c),c===a||b?d.SetVisible(!0):d.SetVisible(!1);this.callbacks.updateMeshesVisibility()};
OV.Menu.prototype.ToggleMeshVisibility=function(a){a=this.modelData.GetMeshData(a);a.SetVisible(!a.IsVisible());this.callbacks.updateMeshesVisibility()};OV.Menu.prototype.GetSelectedMeshIndex=function(){return null!==this.tempSelectedMeshIndex?this.tempSelectedMeshIndex:null===this.selection||this.selection.type!==OV.SelectionType.Mesh?-1:this.selection.index};OV.Menu.prototype.SetTempSelectedMeshIndex=function(a){this.tempSelectedMeshIndex=a;this.callbacks.updateMeshesSelection()};
OV.Menu.prototype.SetSelection=function(a){function b(d,e,f){e.type===OV.SelectionType.Material?d.modelData.GetMaterialData(e.index).SetSelected(f):e.type===OV.SelectionType.Mesh&&d.modelData.GetMeshData(e.index).SetSelected(f)}var c=this.selection;null!==c&&b(this,c,!1);this.selection=a;this.UpdateInfoPanel();this.tempSelectedMeshIndex=null;null!==this.selection&&(null!==c&&this.selection.type===c.type&&this.selection.index===c.index?(b(this,this.selection,!1),this.selection=null,this.UpdateInfoPanel()):
b(this,this.selection,!0));this.callbacks.updateMeshesSelection()};OV.Menu.prototype.FitMeshToWindow=function(a){this.callbacks.fitMeshToWindow(a)};
OV.Menu.prototype.UpdateInfoPanel=function(){var a=this;if(null===this.selection){var b=this.callbacks.getModelInformation();b.usedMaterials=[];for(var c=0;c<this.modelData.MaterialCount();c++)b.usedMaterials.push(c);this.infoPanel.FillWithModelInfo(b,this.callbacks.getMaterialInformation,{onMaterialSelect:function(d){a.SetSelection(new OV.Selection(OV.SelectionType.Material,d))}})}else this.selection.type===OV.SelectionType.Material?(b=this.callbacks.getMaterialInformation(this.selection.index),
this.infoPanel.FillWithMaterialInfo(b,this.callbacks.getMeshInformation,{onMeshHover:function(d){a.SetTempSelectedMeshIndex(d)},onMeshSelect:function(d){a.SetSelection(new OV.Selection(OV.SelectionType.Mesh,d))}})):this.selection.type===OV.SelectionType.Mesh&&(b=this.callbacks.getMeshInformation(this.selection.index),this.infoPanel.FillWithModelInfo(b,this.callbacks.getMaterialInformation,{onMaterialSelect:function(d){a.SetSelection(new OV.Selection(OV.SelectionType.Material,d))}}));this.Resize()};
OV.Menu.prototype.Clear=function(){this.titleDiv.empty();this.treeView.Clear();this.infoPanel.Clear();this.modelData.Clear();this.selection=null};OV.HashHandler=function(){this.skipNextEvent=!1;this.eventListener=null};OV.HashHandler.prototype.SetEventListener=function(a){this.eventListener=a;window.onhashchange=this.OnChange.bind(this)};OV.HashHandler.prototype.SkipNextEventHandler=function(){this.skipNextEvent=!0};OV.HashHandler.prototype.HasHash=function(){return 0<this.GetHash().length};OV.HashHandler.prototype.ClearHash=function(){this.SetHash("")};OV.HashHandler.prototype.GetModelFilesFromHash=function(){return OV.CreateUrlParser(this.GetHash()).GetModelUrls()};
OV.HashHandler.prototype.SetModelFilesToHash=function(a){a=OV.CreateModelUrlParameters(a);this.SetHash(a)};OV.HashHandler.prototype.GetCameraFromHash=function(){return OV.CreateUrlParser(this.GetHash()).GetCamera()};OV.HashHandler.prototype.GetColorFromHash=function(){return OV.CreateUrlParser(this.GetHash()).GetColor()};OV.HashHandler.prototype.GetHash=function(){return window.location.hash.substr(1)};OV.HashHandler.prototype.SetHash=function(a){window.location.hash=a};
OV.HashHandler.prototype.OnChange=function(){this.skipNextEvent?this.skipNextEvent=!1:this.eventListener()};OV.InitModelLoader=function(a,b){var c=null,d=null;a.Init({onLoadStart:function(){var e=c;null!==e&&e.Hide();b.onStart();d=new OV.ProgressDialog;d.Show("Loading Model")},onImportStart:function(){d.SetText("Importing Model")},onVisualizationStart:function(){d.SetText("Visualizing Model")},onModelFinished:function(e,f){d.Hide();b.onFinish(e,f)},onTextureLoaded:function(){b.onRender()},onLoadError:function(e){d.Hide();c=e.code===OV.ImportErrorCode.NoImportableFile?OV.ShowMessageDialog("Something went wrong",
"No importable file found. You can open obj, 3ds, stl, ply, gltf, glb and off files.",e.message):e.code===OV.ImportErrorCode.ImportFailed?OV.ShowMessageDialog("Something went wrong","Failed to import model.",e.message):OV.ShowMessageDialog("Something went wrong","Unknown error.",e.message)}})};OV.Website=function(a){this.parameters=a;this.viewer=new OV.Viewer;this.hashHandler=new OV.HashHandler;this.toolbar=new OV.Toolbar(this.parameters.toolbarDiv);this.menu=new OV.Menu(this.parameters.menuDiv);this.importSettings=new OV.ImportSettings;this.modelLoader=new OV.ThreeModelLoader;this.highlightMaterial=new THREE.MeshPhongMaterial({color:9357808,side:THREE.DoubleSide});this.dialog=this.model=null};
OV.Website.prototype.Load=function(){var a=$("<canvas>").appendTo(this.parameters.viewerDiv);this.viewer.Init(a.get(0));this.ShowViewer(!1);this.hashHandler.SetEventListener(this.OnHashChange.bind(this));this.InitToolbar();this.InitDragAndDrop();this.InitModelLoader();this.InitMenu();this.viewer.SetClickHandler(this.OnModelClicked.bind(this));this.Resize();this.OnHashChange();var b=this;$(window).on("resize",function(){b.Resize()})};
OV.Website.prototype.Resize=function(){var a=$(window).outerWidth(),b=$(window).outerHeight(),c=parseInt(this.parameters.headerDiv.outerHeight(!0),10),d=0,e=0;OV.IsSmallWidth()||(d=parseInt(this.parameters.menuDiv.outerWidth(!0),10),e=1);a=a-d-e;b=b-c-e;this.parameters.menuDiv.outerHeight(b,!0);this.parameters.introDiv.outerHeight(b,!0);this.menu.Resize();this.viewer.Resize(a,b)};OV.Website.prototype.ShowViewer=function(a){a?this.parameters.mainDiv.show():this.parameters.mainDiv.hide()};
OV.Website.prototype.ClearModel=function(){null!==this.dialog&&(this.dialog.Hide(),this.dialog=null);this.model=null;this.parameters.introDiv.hide();this.ShowViewer(!1);this.viewer.Clear();this.menu.Clear()};OV.Website.prototype.OnModelFinished=function(a,b){this.model=a.model;this.ShowViewer(!0);this.viewer.AddMeshes(b);this.viewer.SetUpVector(a.upVector,!1);this.menu.FillTree(a);this.FitModelToWindow(!0)};
OV.Website.prototype.OnModelClicked=function(a,b,c){1===a&&(a=this.viewer.GetMeshUnderMouse(c),null===a?this.menu.SetSelection(null):b?this.menu.IsolateMesh(a.originalMeshIndex):this.menu.SetSelection(new OV.Selection(OV.SelectionType.Mesh,a.originalMeshIndex)))};OV.Website.prototype.OpenFileBrowserDialog=function(){this.parameters.fileInput.trigger("click")};
OV.Website.prototype.FitModelToWindow=function(a){var b=this,c=!a,d=this.viewer.GetBoundingSphere(function(e){return b.menu.IsMeshVisible(e.originalMeshIndex)});a&&this.viewer.AdjustClippingPlanes(d);this.viewer.FitToWindow(d,c)};OV.Website.prototype.FitMeshToWindow=function(a){var b=this.viewer.GetBoundingSphere(function(c){return c.originalMeshIndex===a});this.viewer.FitToWindow(b,!0)};OV.Website.prototype.UpdateMeshesVisibility=function(){var a=this;this.viewer.SetMeshesVisibility(function(b){return a.menu.IsMeshVisible(b.originalMeshIndex)})};
OV.Website.prototype.UpdateMeshesSelection=function(){var a=this.menu.GetSelectedMeshIndex();this.viewer.SetMeshesHighlight(this.highlightMaterial,function(b){return b.originalMeshIndex===a?!0:!1})};OV.Website.prototype.LoadModelFromUrlList=function(a,b){this.modelLoader.LoadFromUrlList(a,b);this.ClearHashIfNotOnlyUrlList()};OV.Website.prototype.LoadModelFromFileList=function(a){this.modelLoader.LoadFromFileList(a,this.importSettings);this.ClearHashIfNotOnlyUrlList()};
OV.Website.prototype.ReloadFiles=function(){null!==this.model&&this.modelLoader.ReloadFiles(this.importSettings)};OV.Website.prototype.ClearHashIfNotOnlyUrlList=function(){!this.modelLoader.GetImporter().IsOnlyFileSource(OV.FileSource.Url)&&this.hashHandler.HasHash()&&(this.hashHandler.SkipNextEventHandler(),this.hashHandler.ClearHash())};
OV.Website.prototype.OnHashChange=function(){if(this.hashHandler.HasHash()){var a=this.hashHandler.GetModelFilesFromHash();if(null!==a){var b=new OV.ImportSettings;b.defaultColor=this.importSettings.defaultColor;var c=this.hashHandler.GetColorFromHash();null!==c&&(b.defaultColor=c);this.LoadModelFromUrlList(a,b)}}else this.ClearModel(),this.parameters.introDiv.show()};
OV.Website.prototype.InitToolbar=function(){function a(d,e,f,g,h){d=d.AddImageButton("assets/images/toolbar/"+e+".svg",f,h);g&&d.AddClass("only_full_width")}function b(d,e){d=d.AddSeparator();e&&d.addClass("only_full_width")}var c=this;this.modelLoader.GetImporter();a(this.toolbar,"fit","Fit model to Window",!1,function(){c.FitModelToWindow(!1)});a(this.toolbar,"up_y","Set Y axis as up vector",!1,function(){c.viewer.SetUpVector(OV.Direction.Y,!0)});a(this.toolbar,"up_z","Set Z axis as up vector",
!1,function(){c.viewer.SetUpVector(OV.Direction.Z,!0)});b(this.toolbar);(function(d,e,f,g,h,l){for(var k=[],n=0;n<e.length;n++)k.push({image:"assets/images/toolbar/"+e[n]+".svg",title:f[n]});d=d.AddImageRadioButton(k,g,l);if(h)for(h=0;h<d.length;h++)d[h].AddClass("only_full_width")})(this.toolbar,["fix_up_on","fix_up_off"],["Fixed up vector","Free orbit"],0,!1,function(d){0===d?c.viewer.SetFixUpVector(!0):1===d&&c.viewer.SetFixUpVector(!1)});OV.FeatureSet.SetDefaultColor&&(b(this.toolbar,!0),a(this.toolbar,
"settings","Settings",!0,function(){c.dialog=OV.ShowSettingsDialog(c.importSettings,function(d){var e=!1;OV.ColorIsEqual(c.importSettings.defaultColor,d.defaultColor)||(c.importSettings.defaultColor=d.defaultColor,e=!0);e&&c.ReloadFiles()})}));this.parameters.fileInput.on("change",function(d){0<d.target.files.length&&c.LoadModelFromFileList(d.target.files)})};
OV.Website.prototype.InitDragAndDrop=function(){window.addEventListener("dragstart",function(b){b.preventDefault()},!1);window.addEventListener("dragover",function(b){b.stopPropagation();b.preventDefault();b.dataTransfer.dropEffect="copy"},!1);var a=this;window.addEventListener("drop",function(b){b.stopPropagation();b.preventDefault();0<b.dataTransfer.files.length&&a.LoadModelFromFileList(b.dataTransfer.files)},!1)};
OV.Website.prototype.InitModelLoader=function(){var a=this;OV.InitModelLoader(this.modelLoader,{onStart:function(){a.ClearModel()},onFinish:function(b,c){a.OnModelFinished(b,c)},onRender:function(){a.viewer.Render()}})};
OV.Website.prototype.InitMenu=function(){function a(g,h){var l=null;g.EnumerateMeshesUserData(function(k){k.originalMeshIndex===h&&(l=k)});return l}function b(g){return null===g?null:{min:new OV.Coord3D(g.min.x,g.min.y,g.min.z),max:new OV.Coord3D(g.max.x,g.max.y,g.max.z)}}function c(g,h,l){function k(m,p,q){null!==q&&m.push({type:p,name:OV.GetFileName(q.name),path:q.name})}h=h.GetMaterial(l);var n={name:h.name,ambient:h.ambient.Clone(),diffuse:h.diffuse.Clone(),specular:h.specular.Clone(),opacity:h.opacity,
textureNames:[],usedByMeshes:[]};k(n.textureNames,"Base",h.diffuseMap);k(n.textureNames,"Specular",h.specularMap);k(n.textureNames,"Bump",h.bumpMap);k(n.textureNames,"Normal",h.normalMap);k(n.textureNames,"Emissive",h.emissiveMap);g.EnumerateMeshesUserData(function(m){-1!==m.originalMaterials.indexOf(l)&&n.usedByMeshes.push(m.originalMeshIndex)});return n}function d(g,h,l){var k={name:null,vertexCount:null,triangleCount:null,usedMaterials:null,boundingBox:null};h=h.GetMesh(l);k.name=h.GetName();k.vertexCount=
h.VertexCount();k.triangleCount=h.TriangleCount();h=a(g,l);k.usedMaterials=h.originalMaterials;k.usedMaterials.sort();g=g.GetBoundingBox(function(n){return n.originalMeshIndex===l});k.boundingBox=b(g);return k}function e(g,h){g={name:null,vertexCount:g.VertexCount(),triangleCount:g.TriangleCount(),usedMaterials:null,boundingBox:null};h=h.GetBoundingBox(function(l){return!0});g.boundingBox=b(h);return g}var f=this;this.menu.Init({openFileBrowserDialog:function(){f.OpenFileBrowserDialog()},updateMeshesVisibility:function(){f.UpdateMeshesVisibility()},
updateMeshesSelection:function(){f.UpdateMeshesSelection()},fitMeshToWindow:function(g){f.FitMeshToWindow(g)},getMaterialInformation:function(g){return c(f.viewer,f.model,g)},getMeshInformation:function(g){return d(f.viewer,f.model,g)},getModelInformation:function(){return e(f.model,f.viewer)}})};OV.Embed=function(a){this.parameters=a;this.viewer=new OV.Viewer;this.hashHandler=new OV.HashHandler;this.modelLoader=new OV.ThreeModelLoader};
OV.Embed.prototype.Load=function(){var a=$("<canvas>").appendTo(this.parameters.viewerDiv);this.viewer.Init(a.get(0));this.InitModelLoader();this.Resize();if(this.hashHandler.HasHash()){a=this.hashHandler.GetModelFilesFromHash();if(null===a)return;var b=new OV.ImportSettings,c=this.hashHandler.GetColorFromHash();null!==c&&(b.defaultColor=c);this.modelLoader.LoadFromUrlList(a,b);a=OV.CreateModelUrlParameters(a);a=this.parameters.websiteLinkDiv.attr("href")+"#"+a;this.parameters.websiteLinkDiv.attr("href",
a)}var d=this;$(window).on("resize",function(){d.Resize()})};OV.Embed.prototype.Resize=function(){var a=$(window).outerWidth(),b=$(window).outerHeight();this.viewer.Resize(a,b)};OV.Embed.prototype.OnModelFinished=function(a,b){this.viewer.AddMeshes(b);b=this.viewer.GetBoundingSphere(function(d){return!0});this.viewer.AdjustClippingPlanes(b);var c=this.hashHandler.GetCameraFromHash();null!==c?this.viewer.SetCamera(c):this.viewer.SetUpVector(a.upVector,!1);this.viewer.FitToWindow(b,!1)};
OV.Embed.prototype.InitModelLoader=function(){var a=this;OV.InitModelLoader(this.modelLoader,{onStart:function(){},onFinish:function(b,c){a.OnModelFinished(b,c)},onRender:function(){a.viewer.Render()}})};
